version: '3.7'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: loan-simulator-postgres
    image: bitnami/postgresql:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
